[build]
  command = "npm run clean && npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --platform=linux --arch=x64"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 